randomize-block-drops: true # Set to true to randomize block loot table
randomize-entity-drops: true # Set to true to randomize entity loot table
randomize-chest-loot: true # Set to true to randomize chest loot table