name: ${project.name}
version: ${project.version}
main: me.fixed.mcrandomizer.MCRandomizerPlugin
description: ${project.description}
author: FiXed
api-version: 1.13

commands:
  randomizer:
    permission: "randomizer.admin"
    description: "Base command for randomizer."

permissions:
  randomizer.admin:
    description: "Gives permission for all /randomizer commands."
    default: op